sudo: required
dist: trusty

language: rust
rust:
  - stable

addons:
  apt:
    packages:
    - build-essential
    - cmake
    - git
    - libavcodec-dev
    - libavformat-dev
    - libdc1394-22-dev
    - libgmp-dev
    - libgtk2.0-dev
    - libjasper-dev
    - libjpeg-dev
    - libpng-dev
    - libswscale-dev
    - libtbb-dev
    - libtbb2
    - libtiff-dev
    - pkg-config
    - xvfb

before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - sudo -E ./.ci/install_cuda.sh
  - sudo -E ./.ci/travis_build_opencv.sh
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - which rustfmt || cargo install rustfmt-nightly

script:
  - cargo build
  - cargo build --no-default-features
  - cargo test --no-default-features
  - cargo build --features gpu
  - cargo doc --features gpu --no-deps
  - find src/*.rs -exec rustfmt {} \;
  # Available until `cargo fmt` landed in stable rust 1.24
  # - cargo fmt -- --write-mode=diff;

notifications:
  email:
    on_success: never

cache:
  timeout: 1000
  directories:
    - $HOME/usr
    - $HOME/.cargo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: target/doc/
  on:
    branch: master
